### ISSUE TITLE
Krol adnotacji 15godzina

### ISSUE THREAD

**Issue by KerukDeveloper** [15godzina/SimpleGenerators#1]
Witaj królu adnotacji, po co dodajesz adnotacje na komendy po czym bierzesz permisje z configu, wie Pan do czego sluży AtomicReference? bo wnioskując po kodzie chyba niestety nie, 
    public static String colorString(String message) {
        if (message.isEmpty()) return "";
        return ChatColor.translateAlternateColorCodes('&', message);
    }
    czemu sprawdzasz czy message jest empty skoro jezeli wiadomosc jest pusta to zawsze zwraca "".

**Comment by 15godzina** [comment]
tako dla zabawy, nwm po co obczajasz projekt ktory ma jakies 6/7 miesiecy ale hf zamykam
